djangokauppa/urls.py
from django.contrib import admin
from django.urls import path
from kauppa import views
from django.contrib.auth import views as auth_views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.etusivu, name='etusivu'),
    path('yhteystiedot', views.yhteystiedot, name='yhteystiedot'),
    path('tietosuojaseloste', views.tietosuojaseloste, name='tietosuojaseloste'),
    path('tuotteet', views.tuotteet, name='tuotteet'),
    path('tuote/<int:tuoteid>', views.tuote_yksityiskohdat, name='tuote_yksityiskohdat'),
    # path('tuote/lisätä',views.lisätä_tuote, name='lisätä_tuote'),
    path('kärry/lisätä/<int:tuoteid>', views.lisätä_kärryyn, name='lisätä_kärryyn'),
    path('kärry/poistaa/<int:tuoteid>', views.poistaa_kärrystä, name='poistaa_kärrystä'),
    path('kärry/poistaatuote/<int:tuoteid>', views.poistaatuote_kärrystä, name='poistaatuote_kärrystä'),
    path('ostoskärry', views.ostoskärry, name='ostoskärry'),
    path('ostaa', views.ostaa, name='ostaa'),
    path('login', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout', auth_views.LogoutView.as_view(next_page='etusivu'), name='logout'),
    path('signup', views.rekisteröinti, name='rekisteröinti'),
]

# This is needed in DEBUG mode for user uploaded images to work
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kauppa/models.py
from django.db import models
from django.utils.translation import gettext as _
from djangokauppa import settings

# Create your models here.
# var tuoteSchema = new Schema({
#     tuoteid: { type: String, required: true, unique: true },
#     nimi: { type: String, required: true },
#     hinta: { type: Number, required: true },
#     lisatiedot: String,
#     valokuvat: [valokuvaSchema],
#     created_at: Date,
#     updated_at: Date
# });

class Tuote(models.Model):
    nimi = models.CharField(max_length=100)
    hinta = models.DecimalField(max_digits=6, decimal_places=2, null=False)
    lisatiedot = models.TextField(_("Lisätiedot"))
    luotu = models.DateField(_("Lisätty"), auto_now=False, auto_now_add=True)
    paivitetty = models.DateField(_("Viimeksi päivitetty"), auto_now=True)
    määrä = models.IntegerField(_("Määrä"), default=0, null=False)
    kuva = models.ImageField(_('Kuva'), upload_to='images', null=False)

    def __str__(self):
        return self.nimi

    class Meta:
        verbose_name_plural = "Tuotteet"

class OstosKärry(models.Model):
    käyttäjä = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Käyttäjän ID"), on_delete=models.CASCADE, null=False, blank=False)
    tuote = models.ForeignKey(Tuote, verbose_name=_("Tuote ID"), on_delete=models.CASCADE, null=False, blank=False)
    määrä = models.IntegerField(_("Määrä"), default=1, null=False)

    def kokonaishinta(self):
        return self.tuote.hinta * self.määrä

    def __str__(self):
        return f'{self.käyttäjä.first_name} - {self.tuote.nimi} x {self.määrä}'

class Ostos(models.Model):
    ostos_pvm = models.DateTimeField(_("Ostoksen PVM"), auto_now=False, auto_now_add=True)
    kokonaishinta = models.DecimalField(max_digits=6, decimal_places=2, null=False)
    käyttäjä = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Käyttäjän ID"), on_delete=models.CASCADE, null=False, blank=False)

    def __str__(self):
        return f'{self.käyttäjä} ({self.ostos_pvm}): {self.kokonaishinta}'
    
class OstoksenTuote(models.Model):
    ostos = models.ForeignKey(Ostos, verbose_name=_("Ostos"), on_delete=models.CASCADE, null=False, blank=False)
    tuote = models.ForeignKey(Tuote, verbose_name=_("Tuote"), on_delete=models.CASCADE, null=False, blank=False)
    määrä = models.IntegerField(_("Määrä"), null=False)
    hinta_per_kpl = models.DecimalField(max_digits=6, decimal_places=2, null=False)

    def __str__(self):
        return f'{self.ostos.käyttäjä.first_name} - {self.tuote.nimi} x {self.määrä}'

kauppa/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.utils.translation import gettext as _
from asiakas.forms import ProfiiliCreationForm
from asiakas.models import Profiili


#
# Käyttäjän rekisteröinti
#
class RekisteröintiLomake(ProfiiliCreationForm):
    first_name = forms.CharField(label='Etunimi', max_length=30, required=False, help_text='Etunimi')
    last_name = forms.CharField(label='Sukunimi', max_length=30, required=False, help_text='Sukunimi')
    email = forms.EmailField(label='Sähköposti', max_length=254, help_text='Laita oikea sähköpostiosoittetta')

    class Meta:
        model = Profiili
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

kauppa/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Tuote, OstosKärry, Ostos, OstoksenTuote
from django import forms
import random
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from datetime import datetime, timezone
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import RekisteröintiLomake


#
# Apufunktiota
#
def laske_tuotteidenmäärä(user):
    ostoslista = OstosKärry.objects.filter(käyttäjä=user)
    if not ostoslista:
        return 0
    määrä = 0
    for item in ostoslista:
        määrä += item.määrä
    return määrä

def laske_kokonaishinta(user):
    ostoslista = OstosKärry.objects.filter(käyttäjä=user)
    if not ostoslista:
        return 0
    hinta = 0
    for item in ostoslista:
        hinta += item.tuote.hinta * item.määrä
    return hinta

#
# Etusivu
#
def etusivu(request):
    korostettu = random.choice(Tuote.objects.filter(määrä__gt="0"))
    context = { 'hero' : korostettu }
    if request.user.is_authenticated:
        context['ostosmäärä'] = laske_tuotteidenmäärä(request.user)
    return render(request, 'etusivu.html', context)

#
# Yhteystiedot
#
def yhteystiedot(request):
    context = {}
    if request.user.is_authenticated:
        context['ostosmäärä'] = laske_tuotteidenmäärä(request.user)
    # return HttpResponse('Yhteystiedot')
    return render(request, 'yhteystiedot.html', context)

#
# Tietosuojaseloste
#
def tietosuojaseloste(request):
    context = {}
    if request.user.is_authenticated:
        context['ostosmäärä'] = laske_tuotteidenmäärä(request.user)
    return render(request, 'tietosuojaseloste.html', context)

#
# Tuotteet
#
def tuotteet(request):
    context = { 'tuotteet': Tuote.objects.filter(määrä__gt="0") }
    if request.user.is_authenticated:
        context['ostosmäärä'] = laske_tuotteidenmäärä(request.user)
    return render(request, 'tuotteet.html', context)


# class UusiTuoteForm(forms.Form):
#     nimi = forms.CharField(label = "Tuotteen nimi:", max_length=100, required = True)
#     esitys = forms.CharField(label = "Tietoa tuotteesta:", widget=forms.Textarea, required = True)
#     hinta = forms.DecimalField(min_value = 0, decimal_places = 2, required = True)
#     määrä = forms.IntegerField(min_value = 0, required = True)

# def lisätä_tuote(request):
#     if request.method == 'POST':
#         tuoteForm = UusiTuoteForm(request.POST)
#         if tuoteForm.is_valid():
#             nimi = tuoteForm.cleaned_data['nimi']
#             esitys = tuoteForm.cleaned_data['esitys']
#             hinta = tuoteForm.cleaned_data['hinta']
#             määrä = tuoteForm.cleaned_data['määrä']
#             tuote = Tuote(nimi=nimi, lisatiedot=esitys, hinta=hinta, määrä=määrä)
#             tuote.save()
#         tuoteForm = NewTuoteForm()
#         return render(request, 'addtuote.html', {'form': tuoteForm})
#     else:
#         tuoteForm = NewTuoteForm()
#         return render(request, 'addtuote.html', {'form': tuoteForm})
#     return redirect('etusivu')

#
# Lisätä tuote kärryyn
#
@login_required(login_url = reverse_lazy('login'))
def lisätä_kärryyn(request, tuoteid):
    tuote_kärryllä = OstosKärry.objects.filter(käyttäjä=request.user, tuote=tuoteid)
    tuote = Tuote.objects.get(id=tuoteid) ## TODO: Mitä jos tuote ei ole olemassa???
    if tuote_kärryllä:
        tuote_kärryllä = tuote_kärryllä[0]
        if tuote.määrä >= tuote_kärryllä.määrä + 1:
            tuote_kärryllä.määrä += 1
    else:
        tuote_kärryllä = OstosKärry.objects.create(käyttäjä=request.user, tuote=tuote)
    tuote_kärryllä.save()
    if 'referer' in request.headers:
        next = request.headers.get('referer')
    else:
        next = reverse(etusivu)
    return redirect(next)
    # return HttpResponse(f'OK: id={id}, user={request.user.id}')

#
# Poista tuote kärrystä (poista 1)
#
@login_required(login_url = reverse_lazy('login'))
def poistaa_kärrystä(request, tuoteid):
    tuote_kärryllä = OstosKärry.objects.filter(käyttäjä=request.user, tuote=tuoteid)
    if tuote_kärryllä:
        tuote_kärryllä = tuote_kärryllä[0]
        tuote_kärryllä.määrä -= 1
        if tuote_kärryllä.määrä ==  0:
            tuote_kärryllä.delete()
        else:
            tuote_kärryllä.save()
    if 'referer' in request.headers:
        next = request.headers.get('referer')
    else:
        next = reverse(etusivu)
    return redirect(next)

#
# Poista tuotetyypi kärrystä
#
@login_required(login_url = reverse_lazy('login'))
def poistaatuote_kärrystä(request, tuoteid):
    tuote_kärryllä = OstosKärry.objects.filter(käyttäjä=request.user, tuote=tuoteid)
    if tuote_kärryllä:
        tuote_kärryllä[0].delete()
    if 'referer' in request.headers:
        next = request.headers.get('referer')
    else:
        next = reverse(etusivu)
    return redirect(next)

#
# Tuotteen yksityiskohdat
#
def tuote_yksityiskohdat(request, tuoteid):
    tuote = get_object_or_404(Tuote, id=tuoteid)
    context = { 'tuote': tuote }
    if request.user.is_authenticated:
        context['ostosmäärä'] = laske_tuotteidenmäärä(request.user)
    return render(request, 'yksityiskohdat.html', context)

#
# Ostöskärry
#
@login_required(login_url = reverse_lazy('login'))
def ostoskärry(request):
    ostoslista = OstosKärry.objects.filter(käyttäjä=request.user)
    context = { 
        'ostoslista': ostoslista,
        'ostosmäärä': laske_tuotteidenmäärä(request.user),
        'kokonaishinta': laske_kokonaishinta(request.user),
    }
    return render(request, 'ostoskärry.html', context)

#
# Ostaa
#
@login_required(login_url = reverse_lazy('login'))
def ostaa(request):
    ostoslista = OstosKärry.objects.filter(käyttäjä=request.user)
    if not ostoslista:
        return redirect('etusivu')
    ostos = Ostos.objects.create(
        käyttäjä=request.user,
        ostos_pvm = datetime.now(timezone.utc),
        kokonaishinta = laske_kokonaishinta(request.user)
    )
    for item in ostoslista:
        ostoksentuote = OstoksenTuote.objects.create(
            ostos = ostos,
            tuote = item.tuote,
            määrä = item.määrä,
            hinta_per_kpl = item.tuote.hinta
        )
        item.tuote.määrä -= item.määrä
        item.tuote.save()
        item.delete()
    return render(request, 'kiitos.html' , { 'ostosmäärä': 0})

#
# Rekisteröinti
#
def rekisteröinti(request):
    if request.method == 'POST':
        lomake = RekisteröintiLomake(request.POST)
        if lomake.is_valid():
            lomake.save()
            username = lomake.cleaned_data.get('username')
            raw_password = lomake.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('etusivu')
    else:
        lomake = RekisteröintiLomake()
    return render(request, 'rekisteröinti.html', {'form': lomake})

kauppa/templates/addtuote.html
{% extends 'base.html' %}

{% block title %}Lisää tuote{% endblock %}

{% block content_title %}Lisää tuote{% endblock %}


{% block content %}
<section class="section">
    <div class="container">
        <form method="POST" novalidate action="{% url 'addtuote' %}">
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="button is-primary">Add product</button>
        </form>
    </div>
</section>
{% endblock %}

kauppa/templates/base.html
<!DOCTYPE html>
<html lang="fi">
<head>
    <title>DjangoKAUPPA | {% block title %}Page Title{% endblock title %}</title>
    {% include 'includes/head.html' %}
    {% block head %}{% endblock head %}
</head>

<body class="container is-max-desktop">

<header class="container mb-6">
    {% include 'includes/navigation.html' %}
</header>

{% block content %}{% endblock content%}

<footer class='footer has-background-black mt-6'>
    {% block footer %}{% endblock footer%}
    {% include 'includes/footer.html' %}
</footer>

<script>
    /* Burger menu functionality */
    let burgerMenu = document.getElementById("burger-menu");
    let navbarMenu = document.getElementById("navbar-menu");
    burgerMenu.addEventListener("click", function () {
    burgerMenu.classList.toggle("is-active");
    navbarMenu.classList.toggle("is-active");
    });
</script>

{% block script %}
{% endblock script %}

</body>
</html>

kauppa/templates/base_etusivu.html
<!DOCTYPE html>
<html lang="fi">
<head>
    <title>DjangoKAUPPA | {% block title %}Page Title{% endblock title %}</title>
    {% include 'includes/head.html' %}
    {% block head %}{% endblock head %}
</head>
<body class="container is-max-desktop">

<header class="container mb-6">
    {% include 'includes/navigation.html' %}
</header>

{% block content %}{% endblock content%}

<footer class='footer has-background-black mt-6'>
    {% block footer %}{% endblock footer%}
    {% include 'includes/footer.html' %}
</footer>

<script>
    /* Burger menu functionality */
    let burgerMenu = document.getElementById("burger-menu");
    let navbarMenu = document.getElementById("navbar-menu");
    burgerMenu.addEventListener("click", function () {
    burgerMenu.classList.toggle("is-active");
    navbarMenu.classList.toggle("is-active");
    });
</script>

</body>
</html>

kauppa/templates/base_no_footer.html
<!DOCTYPE html>
<html lang="fi">
<head>
    <title>DjangoKAUPPA | {% block title %}Page Title{% endblock title %}</title>
    {% include 'includes/head.html' %}
    {% block head %}{% endblock head %}
</head>

<body class="container is-max-desktop">

<header class="container mb-6">
    {% include 'includes/navigation.html' %}
</header>

{% block content %}{% endblock content%}

<script>
    /* Burger menu functionality */
    let burgerMenu = document.getElementById("burger-menu");
    let navbarMenu = document.getElementById("navbar-menu");
    burgerMenu.addEventListener("click", function () {
    burgerMenu.classList.toggle("is-active");
    navbarMenu.classList.toggle("is-active");
    });
</script>

</body>
</html>

kauppa/templates/etusivu.html
{% extends 'base_etusivu.html' %}
{% load static %}

{% block title %}Etusivu{% endblock %}

{% block content %}
<!-- Hero card -->
<div class="section p-0 mb-6">
    <div class="card is-horizontal">

        <div class="card-image">
            <figure class="image is-4by3">
                <img src="{{ hero.kuva.url }}" alt="this used to be photo">
            </figure>
        </div>

        <div class="card-content">
            <p class="title is-3">{{ hero.nimi }}</p>
            <div class="content">{{ hero.lisatiedot }}
                <br><br>
                {% if hero.hinta > 100 %}
                    <span class="tag is-link">Ilmainen lähetys</span>
                {% endif %}
                <span class="tag is-warning">Vain 1 päivä tällä hinnalla!</span>
            </div>
            <p class="is-size-3 mb-3 has-text-centered">Hinta: {{ hero.hinta }}€</p>
            <div class="level"><a class="level-item is-size-4 button is-primary has-text-weight-bold" href="{% url 'lisätä_kärryyn' hero.id %}">
                Lisää ostoskoriin
            </a></div>
        </div>
    </div>
</div>

<!-- Call to Action -->
<div class="cta level mb-6">
    <a class="button level-item has-text-centered is-primary is-rounded" href="{% url 'tuotteet' %}">
        Katso kaikki tuottet täältä!
    </a>
</div>
    

<!-- Info cards -->
<div class="container">
    <div class="columns is-multiline">
        <!-- Card container -->
        <div class="column is-6-tablet is-4-desktop">

            <!-- Card 1 -->
            <div class="card">
                <span class="card-icon has-text-warning">
                    <i class="fas fa-euro-sign"></i>
                </span>
                <div class="card-content">
                        <div class="content">
                            <strong>Aina edullisimmat hinnat</strong>. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga alias pariatur cum deserunt iste atque. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Fuga alias pariatur cum deserunt iste atque.
                        </div>
                </div>
            </div>
        </div>

        <!-- Card container -->
        <div class="column is-6-tablet is-4-desktop">

            <!-- Card 2 -->
            <div class="card">
                <div class="card-icon has-text-danger">
                    <i class="fas fa-award"></i>
                </div>
                <div class="card-content">
                        <div class="content">
                            <strong>Parhaimmat ja laadukkaimmat tuotteet</strong>. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            Phasellus nec iaculis mauris.
                        </div>
                </div>
            </div>
        </div>

        <!-- Card container -->
        <div class="column">

            <!-- Card 3 -->
            <div class="card">
                <div class="card-icon has-text-info">
                    <i class="fas fa-shipping-fast"></i>
                </div>
                <div class="card-content">
                        <div class="content">
                            <strong>Nopea toimitusta!</strong>. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                            Phasellus nec iaculis mauris.
                        </div>
                </div>
            </div>
        </div>

    </div>
</div>
{% endblock content %}

kauppa/templates/kiitos.html
{% extends 'base_no_footer.html' %}
{% load static %}

{% block title %}Kiitos{% endblock %}

{% block content %}
<section class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-8">
                    <div class="box has-background-success-light p-6">
                        <p class="is-size-3 mb-6 has-text-centered has-text-success-dark">Kiitos ostoksesta!</p>
                        <div class="columns">
                            <a href="{% url 'etusivu' %}"><button class="button column is-size-3 is-info mr-1">Palaa etusivuun</button></a>
                            <a href="{% url 'tuotteet' %}"><button class="button column is-size-3 is-primary">Jatkaa ostoksia</button></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

kauppa/templates/login.html
{% extends 'base_no_footer.html' %}
{% load static %}

{% block title %}Kirjautuminen{% endblock %}

{% block content %}
<section class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-7">
                    {% if form.errors %}
                        <div class="notification is-danger is-light">
                            <p>Käyttäjätunnus ja salasana eivät tasmaa. Yritä uudeelleen.</p>
                        </div>
                    {% endif %}

                    {% if next %}
                        {% if user.is_authenticated %}
                            <p>Your account doesn't have access to this page. To proceed,
                        please login with an account that has access.</p>
                        {% else %}
                            <p>Please login to see this page.</p>
                        {% endif %}
                    {% endif %}

                    <form action="{% url 'login' %}" class="box" method="post">
                        {% csrf_token %}
                        <div class="field has-text-centered">
                            <img src="{% static 'kauppa/kuvat/DjangoKauppa_Logo_400.png' %}" width="167">
                        </div>
                        <div class="field">
                            <label class="label">Käyttäjätunnus</label>
                            <div class="control has-icons-left">
                                <input class="input" id="id_username" name="username" autofocus="" autocapitalize="none" autocomplete="username" type="text" placeholder="Käyttäjätunnus" maxlength="30" required>
                                <span class="icon is-small is-left">
                                    <i class="fa fa-user"></i>
                                </span>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Salasana</label>
                            <div class="control has-icons-left">
                                <input id="id_password" class="input" name="password" type="password" placeholder="Salasana" required>
                                <span class="icon is-small is-left">
                                    <i class="fa fa-lock"></i>
                                </span>
                            </div>
                        </div>
                        <div class="field">
                            <button class="button is-success">
                            Kirjaudu sisään
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

kauppa/templates/rekisteröinti.html
{% extends 'base_no_footer.html' %}
{% load static %}

{% block title %}Rekisteröinti{% endblock %}

{% block head %}
<style>
input:focus {
    border-color: rgba(82, 168, 236, 0.8);
    box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset, 0 0 8px rgba(82, 168, 236, 0.6);
    outline: 0 none;
    padding: 0.5rem;
    border-radius: 4px;
}
</style>
{% endblock head %}

{% block content %}
<section class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container">
            <div class="columns is-centered">
                <div class="column is-7">
                    {% comment %} {% if form.errors %}
                        <div class="notification is-danger is-light">
                            <p>Käyttäjätunnus ja salasana eivät tasmaa. Yritä uudeelleen.</p>
                        </div>
                    {% endif %} {% endcomment %}

                    {% if next %}
                        {% if user.is_authenticated %}
                            <p>Your account doesn't have access to this page. To proceed,
                        please login with an account that has access.</p>
                        {% else %}
                            <p>Please login to see this page.</p>
                        {% endif %}
                    {% endif %}

                    <form action="{% url 'rekisteröinti' %}" class="box content" method="post">
                        {% csrf_token %}
                        <div class="field has-text-centered">
                            <img src="{% static 'kauppa/kuvat/DjangoKauppa_Logo_400.png' %}" width="167">
                        </div>

                        {% for field in form %}
                        <p>
                            {{ field.label_tag }}<br>
                            {{ field }}
                            {% if field.help_text %}
                            <br><small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% if field.errors %}
                            <p style="color: red; padding-left: 1rem;">
                            {% for error in field.errors %}
                                {{ error }}<br>
                            {% endfor %}
                            </p>
                            {% endif %}
                        </p>
                        {% endfor %}
{% comment %}                         
                        <div class="field has-text-centered">
                            <img src="{% static 'kauppa/kuvat/DjangoKauppa_Logo_400.png' %}" width="167">
                        </div>
                        <div class="field">
                            <label class="label">Etunimi</label>
                            <div class="control has-icons-left">
                                <input class="input" id="id_etunimi" name="first_name" autofocus="" autocapitalize="none" autocomplete="etunimi" type="text" placeholder="Etunimi" maxlength="30" required>
                                <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Sukunimi</label>
                            <div class="control has-icons-left">
                                <input class="input" id="id_sukunimi" name="last_name" autofocus="" autocapitalize="none" autocomplete="sukunimi" type="text" placeholder="Sukunimi" maxlength="30" required>
                                <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Käyttäjätunnus</label>
                            <div class="control has-icons-left">
                                <input class="input" id="id_username" name="username" autofocus="" autocapitalize="none" autocomplete="username" type="text" placeholder="Käyttäjätunnus" maxlength="30" required>
                                <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Sähköpostiosoite</label>
                            <div class="control has-icons-left">
                                <input class="input" id="id_email" name="email" autofocus="" autocapitalize="none" autocomplete="email" type="text" placeholder="Sähköpostiosoite" maxlength="100" required>
                                <span class="icon is-small is-left"><i class="fa fa-user"></i></span>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Salasana</label>
                            <div class="control has-icons-left">
                                <input id="id_password1" class="input" name="password1" type="password" placeholder="Salasana" required>
                                <span class="icon is-small is-left"><i class="fa fa-lock"></i></span>
                            </div>
                        </div>
                        <div class="field">
                            <label class="label">Salasana uudeelleen</label>
                            <div class="control has-icons-left">
                                <input id="id_password2" class="input" name="password2" type="password" placeholder="Salasana" required>
                                <span class="icon is-small is-left"><i class="fa fa-lock"></i></span>
                            </div>
                        </div> {% endcomment %}
                        <div class="field">
                            <button class="button is-success">Rekisteröi</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

kauppa/templates/yksityiskohdat.html
{% extends 'base_etusivu.html' %}
{% load static %}

{% block title %}Yksityiskohdat{% endblock %}

{% block head %}
<style>
    button.button.is-primary[disabled] {
        background-color: gray;
        color: #eee;
    }
</style>
{% endblock head %}

{% block content %}

<div class="section p-0 mb-6">
    <div class="card is-horizontal">

        <div class="card-image">
            <figure class="image is-4by3">
                <img src="{{ tuote.kuva.url }}" alt="this used to be photo">
            </figure>
        </div>

        <div class="card-content">
            <p class="title is-3">{{ tuote.nimi }}</p>
            <div class="content">
                {{ tuote.lisatiedot }}
                <br><br>
                <p class="is-size-5">
                    Tuote luottu: {{ tuote.luotu }}
                </p>
                <p class="is-size-5">
                    Tuote päivitetty: {{ tuote.paivitetty }}
                </p>
                <p class="is-size-5">
                    Varastossa: 
                    {% if tuote.määrä < 10 %}
                    &lt;10
                    {% elif tuote.määrä < 100 %}
                    &gt;10
                    {% else %}
                    &gt;100
                    {% endif %}
                </p>
                <br><br>
                {% if tuote.hinta > 100 %}
                    <span class="tag is-link">Ilmainen lähetys</span>
                {% endif %}
            </div>
            <p class="is-size-3 mb-3 has-text-centered">Hinta: {{ tuote.hinta }}€</p>
            <a href="{% url 'lisätä_kärryyn' tuote.id %}">
                <button class="button is-primary is-size-4 is-fullwidth has-text-weight-bold" {% if tuote.määrä == 0 %}disabled{% endif %}>Lisää ostoskoriin</button>
            </a>
        </div>
    </div>
</div>
{% endblock content %}